exports.TransactionState = {
  DRAFT: "DRAFT",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
};
exports.ReceivingStatus = {
  NOT_RECEIVED: "NOT_RECEIVED",
  PARTLY_RECEIVED: "PARTLY_RECEIVED",
  RECEIVED: "RECEIVED",
};
exports.DeliveryStatus = {
  NOT_DELIVERED: "NOT_DELIVERED",
  PARTLY_DELIVERED: "PARTLY_DELIVERED",
  DELIVERED: "DELIVERED",
};
exports.PaymentStatus = {
  NOT_PAID: "NOT_PAID",
  PARTLY_PAID: "PARTLY_PAID",
  PAID: "PAID",
};
